version: "3.7"

x-custom:
  platforms: &platforms
    - linux/amd64
    - linux/arm64

services:
  cachr-api:
    image: ghcr.io/purplemonkeydish/cachr-api:${TAG-local-dev}
    build:
      context: .
      cache_from:
        - ghcr.io/purplemonkeydish/cachr-api:nightly
        - ghcr.io/purplemonkeydish/cachr-api:latest
        - ghcr.io/purplemonkeydish/cachr-api
        - ghcr.io/purplemonkeydish/cachr-api-cache:${CACHETAG-local}
        - ghcr.io/purplemonkeydish/cachr-api-cache:main
      cache_to:
        - ghcr.io/purplemonkeydish/cachr-api-cache:${CACHETAG-local}
      args:
        - PROJECT=Cachr.Server
      platforms: *platforms
      x-bake:
        platforms: *platforms

  cachr-ui:
    depends_on:
      - cachr-api
    image: ghcr.io/purplemonkeydish/cachr-ui:${TAG-local-dev}
    build:
      context: .
      cache_from:
        - ghcr.io/purplemonkeydish/cachr-ui:nightly
        - ghcr.io/purplemonkeydish/cachr-ui:latest
        - ghcr.io/purplemonkeydish/cachr-ui
        - ghcr.io/purplemonkeydish/cachr-ui-cache:${CACHETAG-local}
        - ghcr.io/purplemonkeydish/cachr-ui-cache:main
      cache_to:
        - ghcr.io/purplemonkeydish/cachr-ui-cache:${CACHETAG-local}
      args:
        - PROJECT=Cachr.Server.UI
      platforms: *platforms
      x-bake:
        platforms: *platforms
