version: "3.7"

x-custom:
  platforms: &platforms
    - linux/amd64
    - linux/arm64

services:
  cachr-api:
    image: ghcr.io/purplemonkeydish/cachr-api:${TAG-local-dev}
    build:
      context: .
      args:
        - PROJECT=Cachr.Server
      platforms: *platforms
      x-bake:
        platforms: *platforms

  cachr-ui:
    depends_on:
      - cachr-api
    image: ghcr.io/purplemonkeydish/cachr-ui:${TAG-local-dev}
    build:
      context: .
      args:
        - PROJECT=Cachr.Server.UI
      platforms: *platforms
      x-bake:
        platforms: *platforms
