name: benchmark-upload
description: "Finish processing single benchmark report"

# Were we can define the inputs that our action will accept
inputs:
  benchmark-name:
    required: true
    description: "This sets the name of the artifact, and report file."
  benchmark-filter:
    required: false
    description: "Benchmark filter used to select which benchmarks to run"
    default: ''

runs:
  using: "composite"
  steps:
    - run: dotnet run -c Release -property:WarningLevel=0 --project Cachr.Benchmarks -- --job short --filter '${{ inputs.benchmark-filter }}*' -i
      shell: bash
    - run: mv BenchmarkDotNet.Artifacts/results/*-report-full-compressed.json ./report-${{ inputs.benchmark-name }}.json
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
       name: benchmark-report-${{ inputs.benchmark-name }}
       path: ./report-${{ inputs.benchmark-name }}.json
