name: "foo"
description: ""
outputs:
  version-suffix:
    description: "A version suffix to be supplied to dotnet tooling"
  version-prefix:
    description: "The version prefix to supply to dotnet tooling"

runs:
  using: "composite"
  steps:
    - shell: bash
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/staging' # 0.1.<BUILD>-dev-SHA
      run: |
        echo "set-output name=version-prefix::0.1"
        echo "::set-output name=version-prefix::0.1"
    - shell: bash
      if: github.ref != 'refs/heads/main' && github.ref != 'refs/heads/staging' # 0.1.<BUILD>-dev-SHA
      run: |
        echo "set-output name=version-suffix::dev-$GITHUB_SHA"
        echo "::set-output name=version-suffix::dev-$GITHUB_SHA"
    - shell: bash
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
      run: |
        echo "set-output name=version-prefix::$(cat version.txt | grep -v '#' | head -n 1)"
        echo "::set-output name=version-prefix::$(cat version.txt | grep -v '#' | head -n 1)"
    - shell: bash
      if: github.ref == 'refs/heads/staging' # <version.txt>.<BUILD>-prerelease-timestamp
      run: |
        echo "set-output name=version-suffix::prerelease-$(date +%Y%j%H%M%S)"
        echo "::set-output name=version-suffix::prerelease-$(date +%Y%j%H%M%S)"
    - shell: bash
      if: github.ref == 'refs/heads/main' # <version.txt>.<BUILD>
      run: |
        echo "set-output name=version-suffix::"
        echo "::set-output name=version-suffix::"
