// <auto-generated />
using System;
using Cachr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cachr.Core.Migrations
{
    [DbContext(typeof(ObjectStorageContext))]
    [Migration("20230715173909_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cachr.Core.Data.StoredObject", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<long>("Created")
                        .HasColumnType("bigint");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("uuid");

                    b.Property<long>("Modified")
                        .HasColumnType("bigint");

                    b.Property<int>("Shard")
                        .HasColumnType("integer");

                    b.HasKey("Key");

                    b.HasIndex("MetadataId")
                        .IsUnique();

                    b.ToTable("StoredObjects");
                });

            modelBuilder.Entity("Cachr.Core.Data.StoredObjectMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<long?>("AbsoluteExpiration")
                        .HasColumnType("bigint");

                    b.Property<long>("Created")
                        .HasColumnType("bigint");

                    b.Property<long>("LastAccess")
                        .HasColumnType("bigint");

                    b.Property<long>("Modified")
                        .HasColumnType("bigint");

                    b.Property<double?>("SlidingExpiration")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("ObjectMetadata");
                });

            modelBuilder.Entity("Cachr.Core.Data.StoredObject", b =>
                {
                    b.HasOne("Cachr.Core.Data.StoredObjectMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
