// <auto-generated />
using System;
using Cachr.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cachr.Core.Migrations
{
    [DbContext(typeof(ObjectStorageContext))]
    [Migration("20230714194136_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Cachr.Core.Data.StoredObject", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("MetadataId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shard")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.HasIndex("MetadataId")
                        .IsUnique();

                    b.ToTable("StoredObjects");
                });

            modelBuilder.Entity("Cachr.Core.Data.StoredObjectMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long?>("AbsoluteExpiration")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Created")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastAccess")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Modified")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SlidingExpiration")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ObjectMetadata");
                });

            modelBuilder.Entity("Cachr.Core.Data.StoredObject", b =>
                {
                    b.HasOne("Cachr.Core.Data.StoredObjectMetadata", "Metadata")
                        .WithMany()
                        .HasForeignKey("MetadataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Metadata");
                });
#pragma warning restore 612, 618
        }
    }
}
