name: prepare
description: "Prepares for building by installing the required .NET versions, restoring cache, and restoring NuGet packages"

inputs:
  dotnet-version:
    required: false
    default: |
      6.0.x
      7.0.x
    description: "Sets the framework versions to install"
  restore-packages:
    required: false
    default: true
    description: "Controls if we restore NuGet packages"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        include-prerelease: true
    - uses: actions/cache@v3
      id: cache-nuget
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}-${{ hashFiles('**/*.csproj')}}
        restore-keys: ${{ runner.os }}-nuget-
    - uses: actions/cache@v3
      id: cache-binaries
      if: steps.cache-nuget.outputs.cache-hit == 'true'
      with:
        path: |
          **/obj/**/*
          **/bin/**/*
        key: ${{ runner.os }}-bin-${{ hashFiles('**/packages.lock.json') }}-${{hashFiles('**/*.cs')}}-${{ hashFiles('**/*.csproj')}}
    - shell: bash
      if: steps.cache-nuget.outputs.cache-hit != 'true' && steps.cache-binaries.outputs.cache-hit != 'true'
      run: dotnet restore
