name: benchmark-upload
description: "Finish processing single benchmark report"

# Were we can define the inputs that our action will accept
inputs:
  report-path:
    required: true
    description: "Path of the report file to import"
  github-token:
    required: true
    description: "Github token"
  name:
    required: true
    description: "Benchmark name"
  push-pages:
    required: true
    description: 'Indicates if this is the main branch, which will disable comments and failures, and enable pushing'
  comment:
    required: true
    description: "Controls if we post a comment on the commit or not."

runs:
  using: "composite"
  steps:
    - uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'benchmarkdotnet'
        output-file-path: ${{ inputs.report-path }}
        alert-threshold: '200%'
        comment-on-alert: ${{ inputs.comment }}
        comment-always: false
        fail-on-alert: false
        auto-push: ${{ inputs.push-pages }}
        github-token: ${{ inputs.github-token }}
        benchmark-data-dir-path: ""
        name: ${{ inputs.name }}
