name: "Benchmarks"
on:
  push:
    branches:
      - 'main'
  pull_request: { }
concurrency:
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.pull_request.number) || github.head_ref }}
  cancel-in-progress: true
jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    name: "Generate benchmark matrix"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/template/prepare
      - uses: ./.github/template/build
        with:
          runtime-version: net6.0
      - id: set-matrix
        run: |
          echo "Building matrix from files names containing the word Benchmark, and ending with .cs"
          matrix=$(echo '{ "name": '$(dotnet run --project Cachr.Benchmarks --no-build -c Release -r net6.0 -- --list flat | rev | cut -d "." -f 2- | rev | uniq | jq -ncR '[inputs]' | cat), '"os": [ "ubuntu-latest", "macos-latest", "windows-latest" ]}')
          echo $matrix
          echo $matrix | jq .
          echo "::set-output name=matrix::$matrix"

  run:
    runs-on: ${{matrix.os}}
    needs:
      - 'generate_matrix'
    strategy:
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    name: "Benchmark - ${{ matrix.name }} - ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/template/prepare
      - uses: ./.github/template/benchmark
        with:
          benchmark-name: ${{ matrix.name }}-${{ matrix.os }}
          benchmark-filter: ${{ matrix.name }}
  report_results:
    runs-on: ubuntu-latest
    needs:
      - 'generate_matrix'
      - 'run'
    strategy:
      max-parallel: 1
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}
    name: "Finalize - ${{ matrix.name }} - ${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        name: "Download artifacts for ${{ matrix.name }} - ${{ matrix.os }}"
        with:
          name: benchmark-report-${{ matrix.name }}-${{ matrix.os }}
      - uses: "./.github/template/benchmark-upload"
        name: "Report benchmark results for ${{ matrix.name }} - ${{ matrix.os }}"
        with:
          report-path: ./report-${{ matrix.name }}-${{ matrix.os }}.json
          name: Benchmark - ${{ matrix.name }} - ${{ matrix.os }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-pages: ${{ github.ref == 'refs/heads/main' }}
          comment: ${{ github.ref != 'refs/heads/main' }}
