name: "Benchmarks"
on:
  push:
    branches:
      - 'main'
  pull_request: { }
concurrency:
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.pull_request.number) || github.head_ref }}
  cancel-in-progress: true
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: "all"
            filter: ''
    name: "Benchmark - ${{ matrix.name }}"
    steps:
      - uses: actions/checkout@v1
      - uses: './.github/template/benchmark'
        with:
          benchmark-name: ${{ matrix.name }}
          benchmark-filter: ${{ matrix.filter }}
  report_results:
    runs-on: ubuntu-latest
    needs:
      - 'run'
    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: "all"
            first: true
    name: "Finalize - ${{ matrix.name }}"
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v3
        name: "Download artifacts for ${{ matrix.name }}"
        with:
          name: benchmark-report-${{ matrix.name }}
      - uses: "./.github/template/benchmark-upload"
        with:
          output-file-path: ./report-${{ matrix.name }}.json
