name: "build"
on:
  push:
    branches:
      - 'main'
  pull_request: { }
jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
       - uses: actions/setup-dotnet@v2
         with:
           dotnet-version: '6.0.x'
       - uses: actions/cache@v3
         with:
           path: ~/.nuget/packages
           key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
           restore-keys: ${{ runner.os }}-nuget-
       - run: dotnet restore
  test:
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - run: dotnet test
  benchmark:
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - run: dotnet build -c Release -property:WarningLevel=0 Cachr.Benchmarks
      - run: dotnet run -c Release --no-build --project Cachr.Benchmarks -- -j short
      - name: Store DuplicateTrackerBenchmarks result
        uses: rhysd/github-action-benchmark@v1
        with:
          tool: 'benchmarkdotnet'
          output-file-path: BenchmarkDotNet.Artifacts/results/Cachr.Benchmarks.DuplicateTrackerBenchmarks-report-full-compressed.json
          alert-threshold: '200%'
          comment-on-alert: true
          comment-always: true
          fail-on-alert: true
          auto-push: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build_test_report:
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: test
        uses: zyborg/dotnet-tests-report@v1
        with:
          report_name: unit_tests
          report_title: Unit Test Results
          set_check_status_from_test_outcome: true
          extra_test_parameters: '-property:WarningLevel=0'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_xunit.md
          gist_badge_label: 'Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
  build_release_configuration:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - run: dotnet restore
      - run: dotnet build --no-restore -c Release -property:WarningLevel=0
  build_status_comment_failed:
    runs-on: ubuntu-latest
    if: failure() && github.event_name == 'pull_request'
    needs:
      - build_release_configuration
      - build_test_report
    steps:
      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Oops, your build has failed. Please fix the build errors and try again! :) '
          comment_includes: 'your build has started'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
