name: "build"
on: 
  push:
    branches: 
      - 'main'
  pull_request: { }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Restore Packages
        run: dotnet restore
      - name: Build solution
        run: dotnet build --no-restore
      - name: Execute .NET tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          report_name: cachr_unit_tests
          report_title: Cachr Unit Tests
          set_check_status_from_test_outcome: true
          no_restore: true
          no_build: true
          extra_test_parameters: '-warn 0'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_xunit.md
          gist_badge_label: 'Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
      - name: Build release mode
        run: dotnet build --no-restore -c Release -warn 0
      