name: "Build"
on:
  push:
    branches:
      - 'main'
  pull_request: { }
concurrency:
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.pull_request.number) || github.head_ref }}
  cancel-in-progress: true
jobs:
  build_release:
    name: "Build release on ${{matrix.os}}"
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/template/prepare
      - uses: ./.github/template/build
        with:
          configuration: "Release"
  build_debug:
    name: "Build debug on ${{matrix.os}}"
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/template/prepare
      - uses: ./.github/template/build
        with:
          configuration: "Debug"
  build-and-report-warnings:
    name: "Project Builds"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/template/prepare
      - uses: ./.github/template/build
        with:
          configuration: Release
          no-warnings: false
      - uses: ./.github/template/build
        with:
          configuration: Debug
          no-warnings: true
