name: 'Unit Tests'
on:
  push:
    branches:
      - 'main'
  pull_request: { }
concurrency:
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.pull_request.number) || github.head_ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - run: dotnet test
  test_status_comment:
    name: 'Comment test status'
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: 'Failure Comment'
        uses: thollander/actions-comment-pull-request@v1
        if: failure() && github.event_name == 'pull_request'
        with:
          message: 'Tests are failing, Your changes will not be reviewed until tests pass'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Success Comment'
        uses: thollander/actions-comment-pull-request@v1
        if: success() && github.event_name == 'pull_request'
        with:
          message: ':heavy_check_mark: - Unit tests have passed.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

