name: 'Unit Tests'
on:
  push:
    branches:
      - 'main'
  pull_request: { }
concurrency:
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.pull_request.number) || github.head_ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    name: "Unit Tests}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            7.0.x
          include-prerelease: false
      - uses: actions/cache@v3
        id: cache-nuget
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}-${{ hashFiles('**/*.csproj')}}
      - uses: zyborg/dotnet-tests-report@v1
        if: github.ref != 'refs/heads/main'
        with:
          report_name: unit-tests-${{matrix.os}}
          report_title: Unit Test Results - ${{matrix.os}}
          set_check_status_from_test_outcome: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: cachr-test-report-${{matrix.os}}.md
          gist_badge_label: 'Tests (${{matrix.os}}): %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}
          fail_build_on_failed_tests: true
  test-status: # this is for PR checks only
    runs-on: ubuntu-latest
    needs:
      - test
    if: github.ref != 'refs/heads/main'
    steps:
      - run: echo "" > /dev/null
        if: success()
      - run: exit 1
        if: success() != true
