name: "unit-test-reports"
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-
      - name: Execute .NET tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          report_name: cachr_unit_tests
          report_title: Cachr Unit Tests
          set_check_status_from_test_outcome: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gist_name: dotnet-tests-report_xunit.md
          gist_badge_label: 'Tests: %Counters_passed%/%Counters_total%'
          gist_token: ${{ secrets.GIST_TOKEN }}